<?php

return [
     
    'prune_days' => env('APP_ACTIVITY_PRUNE_DAYS', 90),

    // If set to true activity log entries generated by an admin user that is not also
     
     
     
    'hide_admin_activity' => env('APP_ACTIVITY_HIDE_ADMIN', false),
];
